<Project>
  <ItemGroup>
  <None Include="$(MSBuildThisFileDirectory)appsettings.json"
          Condition="Exists('$(MSBuildThisFileDirectory)appsettings.json')"
          Link="appsettings.json"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>